### ISSUE TITLE
[Bug]: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by trungnt1008** [apivideo/api.video-nodejs-client#116]
### Version

2.3.1

### Environment that reproduces the issue

Nodejs

### Is it reproducible in the example application?

Yes

### Reproduction steps

I'm using lib for nodejs server

const video = await client.videos.create(videoCreationPayload);

But it return  connect ECONNREFUSED 127.0.0.1:443

### Expected result

success and return video info (videoId...)

### Actual result

connect ECONNREFUSED 127.0.0.1:443

**Comment by olivierapivideo** [comment]
Hi @trungnt1008 

That's weird, the API client is not supposed to try connect to 127.0.0.1. Can you send us your code?

**Comment by trungnt1008** [comment]
I'm using your example code: 

 const client = new ApiVideoClient({ apiKey: "YOUR_API_KEY" });

        // create a video
        const videoCreationPayload = {
            title: "Maths video", // The title of your new video.
            description: "A video about string theory.", // A brief description of your video.
        };
        const video = await client.videos.create(videoCreationPayload);

But it can't create video and throw exception connect ECONNREFUSED 127.0.0.1:443.

I'm using express nodejs.

So I'm using axios to call method in document, it was success. I think your lib is not working.

 const videoInfo = await axios.post('https://sandbox.api.video/videos', {payloadVideoCreation}, {
        auth: {
          username: configVideo.token,
          password: ''
        }
      });

**Comment by trungnt1008** [comment]
It's my code throw error  connect ECONNREFUSED 127.0.0.1:443

const ApiVideoClient = require('@api.video/nodejs-client').default;

const client = new ApiVideoClient({ apiKey: configVideo.token, baseUri: 'https://sandbox.api.video' });
      // create a video
      const videoCreationPayload = {
        title: "Maths video", // The title of your new video.
        description: "A video about string theory.", // A brief description of your video.
      };
      const video = await client.videos.create(videoCreationPayload);
      console.log(video)

**Comment by olivierapivideo** [comment]
Hey @trungnt1008 ,

I just tested your code and I had no issue. 
Seeing yuor error, It really looks like if you were trying to instantiate a server that listen to the port 433. Is this not the case?
Do you have a full stracktrace of the error?

**Comment by manimaghsoudlou** [comment]
Hi I'm getting the same error, I installed your library yesterday, using version `v2.3.2`:

```
RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:326:22)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:428:9)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:483:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1686766222680,
    socket: 1686766222682,
    lookup: 1686766222684,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1686766222685,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 2,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 5
    }
  }
}
```

The weird thing is, when I run the code as a simple node script outside docker container it works fine. But when I run it inside docker container, then it fails with the above error.

Could you please help me with this?
